// Bets autorizadas pela Secretaria de Prêmios e Apostas (SPA/MF) a operar
// apostas de quota fixa em âmbito nacional. Extraído da tabela oficial em
// https://www.gov.br/fazenda/pt-br/composicao/orgaos/secretaria-de-premios-e-apostas/lista-de-empresas/empresas-autorizadas
// (atualizada em 14/09/2026): 188 marcas.
//
// A lista muda quando a SPA autoriza ou revoga empresas — conferir a página
// oficial de tempos em tempos. Os ícones são os favicons dos domínios .bet.br,
// baixados uma vez para public/casas/ (sem depender de terceiros em cada
// acesso). Casa sem ícone mostra as iniciais; sem domínio é porque a própria
// lista oficial ainda o traz como "a definir".

export type CasaDeAposta = {
  nome: string;
  dominio: string | null;
  icone: string | null;
};

export const CASAS_DE_APOSTA: CasaDeAposta[] = [
  { nome: "1 PRA 1", dominio: "1pra1.bet.br", icone: "/casas/1pra1.png" },
  { nome: "1XBET", dominio: "1xbet.bet.br", icone: "/casas/1xbet.png" },
  { nome: "4PLAY", dominio: "4play.bet.br", icone: "/casas/4play.png" },
  { nome: "4WIN", dominio: "4win.bet.br", icone: "/casas/4win.png" },
  { nome: "55W", dominio: "55w.bet.br", icone: null },
  { nome: "5G", dominio: "5g.bet.br", icone: null },
  { nome: "6R", dominio: "6r.bet.br", icone: "/casas/6r.png" },
  { nome: "6Z", dominio: "6z.bet.br", icone: "/casas/6z.png" },
  { nome: "7GAMES", dominio: "7games.bet.br", icone: "/casas/7games.png" },
  { nome: "7K", dominio: "7k.bet.br", icone: "/casas/7k.png" },
  { nome: "9D", dominio: "9d.bet.br", icone: "/casas/9d.png" },
  { nome: "9F", dominio: "9f.bet.br", icone: "/casas/9f.png" },
  { nome: "A247", dominio: "a247.bet.br", icone: "/casas/a247.png" },
  { nome: "AFUN", dominio: "afun.bet.br", icone: "/casas/afun.png" },
  { nome: "AI", dominio: "ai.bet.br", icone: "/casas/ai.png" },
  { nome: "ALFA.BET", dominio: "alfa.bet.br", icone: "/casas/alfa.png" },
  { nome: "APOSTA1", dominio: "aposta1.bet.br", icone: "/casas/aposta1.png" },
  { nome: "APOSTA BET", dominio: "aposta.bet.br", icone: "/casas/aposta.png" },
  { nome: "APOSTA GANHA", dominio: "apostaganha.bet.br", icone: "/casas/apostaganha.png" },
  { nome: "APOSTAMAX", dominio: "apostamax.bet.br", icone: "/casas/apostamax.png" },
  { nome: "APOSTAR", dominio: "apostar.bet.br", icone: "/casas/apostar.png" },
  { nome: "APOSTATUDO", dominio: "apostatudo.bet.br", icone: "/casas/apostatudo.png" },
  { nome: "APOSTOU", dominio: "apostou.bet.br", icone: "/casas/apostou.png" },
  { nome: "ARENAPLUS", dominio: "arenaplus.bet.br", icone: null },
  { nome: "AVIÃOBET", dominio: "aviao.bet.br", icone: "/casas/aviao.png" },
  { nome: "B1 BET", dominio: "b1bet.bet.br", icone: "/casas/b1bet.png" },
  { nome: "BACANAPLAY", dominio: "bacanaplay.bet.br", icone: "/casas/bacanaplay.png" },
  { nome: "BANDBET", dominio: "bandbet.bet.br", icone: "/casas/bandbet.png" },
  { nome: "BATEU BET", dominio: "bateu.bet.br", icone: "/casas/bateu.png" },
  { nome: "BAÚ BINGO", dominio: "bau.bet.br", icone: null },
  { nome: "BET365", dominio: "bet365.bet.br", icone: "/casas/bet365.png" },
  { nome: "BET4", dominio: "bet4.bet.br", icone: "/casas/bet4.png" },
  { nome: "BET AKI", dominio: "betaki.bet.br", icone: "/casas/betaki.png" },
  { nome: "BETANO", dominio: "betano.bet.br", icone: "/casas/betano.png" },
  { nome: "BETÃO", dominio: "betao.bet.br", icone: "/casas/betao.png" },
  { nome: "BET.APP", dominio: "betapp.bet.br", icone: "/casas/betapp.png" },
  { nome: "BET.BET", dominio: "betpontobet.bet.br", icone: "/casas/betpontobet.png" },
  { nome: "BETBOO", dominio: "betboo.bet.br", icone: "/casas/betboo.png" },
  { nome: "BETBOOM", dominio: "betboom.bet.br", icone: "/casas/betboom.png" },
  { nome: "BETBRA", dominio: "betbra.bet.br", icone: "/casas/betbra.png" },
  { nome: "BET BUFFALOS", dominio: "betbuffalos.bet.br", icone: "/casas/betbuffalos.png" },
  { nome: "BETCAIXA", dominio: "betcaixa.bet.br", icone: null },
  { nome: "BETCOPA", dominio: "betcopa.bet.br", icone: null },
  { nome: "BET DA SORTE", dominio: "betdasorte.bet.br", icone: "/casas/betdasorte.png" },
  { nome: "BET DO MILHÃO", dominio: "milhao.bet.br", icone: "/casas/milhao.png" },
  { nome: "BETESPECIAL", dominio: "betespecial.bet.br", icone: "/casas/betespecial.png" },
  { nome: "BETESPORTE", dominio: "betesporte.bet.br", icone: "/casas/betesporte.png" },
  { nome: "BETFAIR", dominio: "betfair.bet.br", icone: "/casas/betfair.png" },
  { nome: "BET FALCONS", dominio: "betfalcons.bet.br", icone: "/casas/betfalcons.png" },
  { nome: "BETFAST", dominio: "betfast.bet.br", icone: "/casas/betfast.png" },
  { nome: "BETFUSION", dominio: "betfusion.bet.br", icone: "/casas/betfusion.png" },
  { nome: "BETGO", dominio: "betgo.bet.br", icone: "/casas/betgo.png" },
  { nome: "BET GORILLAS", dominio: "betgorillas.bet.br", icone: "/casas/betgorillas.png" },
  { nome: "BETMGM", dominio: "betmgm.bet.br", icone: "/casas/betmgm.png" },
  { nome: "BETNACIONAL", dominio: "betnacional.bet.br", icone: "/casas/betnacional.png" },
  { nome: "BETOU", dominio: "betou.bet.br", icone: "/casas/betou.png" },
  { nome: "BETPIX365", dominio: "betpix365.bet.br", icone: "/casas/betpix365.png" },
  { nome: "BETSSON", dominio: "betsson.bet.br", icone: "/casas/betsson.png" },
  { nome: "BET SUL", dominio: "betsul.bet.br", icone: "/casas/betsul.png" },
  { nome: "BETVIP", dominio: "betvip.bet.br", icone: "/casas/betvip.png" },
  { nome: "BETWARRIOR", dominio: "betwarrior.bet.br", icone: "/casas/betwarrior.png" },
  { nome: "BIG", dominio: "big.bet.br", icone: "/casas/big.png" },
  { nome: "BINGO", dominio: "bingo.bet.br", icone: "/casas/bingo.png" },
  { nome: "BINGOPLUS", dominio: "bingoplus.bet.br", icone: "/casas/bingoplus.png" },
  { nome: "BLAZE", dominio: "blaze.bet.br", icone: "/casas/blaze.png" },
  { nome: "BOLSA DE APOSTA", dominio: "bolsadeaposta.bet.br", icone: "/casas/bolsadeaposta.png" },
  { nome: "BR4BET", dominio: "br4.bet.br", icone: "/casas/br4.png" },
  { nome: "BRA", dominio: "bra.bet.br", icone: "/casas/bra.png" },
  { nome: "BRASIL.BET", dominio: "brasil.bet.br", icone: "/casas/brasil.png" },
  { nome: "BRASIL DA SORTE", dominio: "brasildasorte.bet.br", icone: "/casas/brasildasorte.png" },
  { nome: "BRAVO", dominio: "bravo.bet.br", icone: "/casas/bravo.png" },
  { nome: "BRAZINO777", dominio: "brazino777.bet.br", icone: "/casas/brazino777.png" },
  { nome: "BRBET", dominio: "brbet.bet.br", icone: "/casas/brbet.png" },
  { nome: "BRXBET", dominio: "brx.bet.br", icone: "/casas/brx.png" },
  { nome: "BULLSBET", dominio: "bullsbet.bet.br", icone: "/casas/bullsbet.png" },
  { nome: "BZ", dominio: "bz.bet.br", icone: null },
  { nome: "CASA DE APOSTAS", dominio: "casadeapostas.bet.br", icone: "/casas/casadeapostas.png" },
  { nome: "CASSINO", dominio: "cassino.bet.br", icone: "/casas/cassino.png" },
  { nome: "CBESPORTES", dominio: "cbesportes.bet.br", icone: "/casas/cbesportes.png" },
  { nome: "CGG", dominio: "cgg.bet.br", icone: null },
  { nome: "DONALDBET", dominio: "donald.bet.br", icone: "/casas/donald.png" },
  { nome: "DONOSDABOLA", dominio: "donosdabola.bet.br", icone: "/casas/donosdabola.png" },
  { nome: "DR.BINGO", dominio: "drbingo.bet.br", icone: "/casas/drbingo.png" },
  { nome: "ENERGIA", dominio: "energia.bet.br", icone: "/casas/energia.png" },
  { nome: "ESPORTE 365", dominio: "esporte365.bet.br", icone: "/casas/esporte365.png" },
  { nome: "ESPORTES DA SORTE", dominio: "esportesdasorte.bet.br", icone: "/casas/esportesdasorte.png" },
  { nome: "ESPORTIVA BET", dominio: "esportiva.bet.br", icone: "/casas/esportiva.png" },
  { nome: "ESPORTIVAVIP", dominio: "esportivavip.bet.br", icone: "/casas/esportivavip.png" },
  { nome: "ESTRELABET", dominio: "estrelabet.bet.br", icone: "/casas/estrelabet.png" },
  { nome: "F12.BET", dominio: "f12.bet.br", icone: "/casas/f12.png" },
  { nome: "FANBIT", dominio: "fanbit.bet.br", icone: null },
  { nome: "FAZ1BET", dominio: "faz1.bet.br", icone: "/casas/faz1.png" },
  { nome: "FAZ O BET", dominio: "fazo.bet.br", icone: "/casas/fazo.png" },
  { nome: "FOGO777", dominio: "fogo777.bet.br", icone: "/casas/fogo777.png" },
  { nome: "FREE", dominio: "free.bet.br", icone: null },
  { nome: "FULLTBET", dominio: "fulltbet.bet.br", icone: "/casas/fulltbet.png" },
  { nome: "FYBET", dominio: "fybet.bet.br", icone: null },
  { nome: "GALERA.BET", dominio: "galera.bet.br", icone: "/casas/galera.png" },
  { nome: "GANHEIBET", dominio: "ganhei.bet.br", icone: "/casas/ganhei.png" },
  { nome: "GERALBET", dominio: "geralbet.bet.br", icone: "/casas/geralbet.png" },
  { nome: "GINGABET", dominio: "ginga.bet.br", icone: "/casas/ginga.png" },
  { nome: "GOL DE BET", dominio: "goldebet.bet.br", icone: "/casas/goldebet.png" },
  { nome: "H2 BET", dominio: "h2.bet.br", icone: "/casas/h2.png" },
  { nome: "HILGARDO", dominio: null, icone: null },
  { nome: "HILGARDO GAMING", dominio: null, icone: null },
  { nome: "HIPERBET", dominio: "hiper.bet.br", icone: "/casas/hiper.png" },
  { nome: "ICE", dominio: "ice.bet.br", icone: "/casas/ice.png" },
  { nome: "IJOGO", dominio: "ijogo.bet.br", icone: "/casas/ijogo.png" },
  { nome: "JOGA JUNTO", dominio: "jogajunto.bet.br", icone: "/casas/jogajunto.png" },
  { nome: "JOGA LIMPO", dominio: "jogalimpo.bet.br", icone: null },
  { nome: "JOGÃO", dominio: "jogao.bet.br", icone: "/casas/jogao.png" },
  { nome: "JOGO DE OURO", dominio: "jogodeouro.bet.br", icone: "/casas/jogodeouro.png" },
  { nome: "JOGO ONLINE", dominio: "jogoonline.bet.br", icone: null },
  { nome: "JOGOS", dominio: "jogos.bet.br", icone: null },
  { nome: "JONBET", dominio: "jonbet.bet.br", icone: "/casas/jonbet.png" },
  { nome: "KBET", dominio: "kbet.bet.br", icone: null },
  { nome: "KING PANDA", dominio: "kingpanda.bet.br", icone: "/casas/kingpanda.png" },
  { nome: "KTO", dominio: "kto.bet.br", icone: "/casas/kto.png" },
  { nome: "LANCE DE SORTE", dominio: "lancedesorte.bet.br", icone: "/casas/lancedesorte.png" },
  { nome: "LÍDERBET", dominio: "lider.bet.br", icone: "/casas/lider.png" },
  { nome: "LOTOGREEN", dominio: "lotogreen.bet.br", icone: "/casas/lotogreen.png" },
  { nome: "LOTTOLAND", dominio: "lottoland.bet.br", icone: "/casas/lottoland.png" },
  { nome: "LOTTU", dominio: "lottu.bet.br", icone: "/casas/lottu.png" },
  { nome: "LUCK.BET", dominio: "luck.bet.br", icone: "/casas/luck.png" },
  { nome: "LUVA.BET", dominio: "luva.bet.br", icone: "/casas/luva.png" },
  { nome: "MAGICJACKPOT", dominio: "magicjackpot.bet.br", icone: null },
  { nome: "MATCHBOOK", dominio: "matchbook.bet.br", icone: "/casas/matchbook.png" },
  { nome: "MAXIMABET", dominio: "maxima.bet.br", icone: "/casas/maxima.png" },
  { nome: "MCGAMES", dominio: "mcgames.bet.br", icone: "/casas/mcgames.png" },
  { nome: "MEGABET", dominio: "megabet.bet.br", icone: null },
  { nome: "MEGAPOSTA", dominio: "megaposta.bet.br", icone: "/casas/megaposta.png" },
  { nome: "MERIDIAN", dominio: "meridianbet.bet.br", icone: "/casas/meridianbet.png" },
  { nome: "MGM", dominio: "mgm.bet.br", icone: "/casas/mgm.png" },
  { nome: "MMA", dominio: "mmabet.bet.br", icone: "/casas/mmabet.png" },
  { nome: "MONTECARLOS", dominio: "montecarlos.bet.br", icone: null },
  { nome: "MULTIBET", dominio: "multi.bet.br", icone: "/casas/multi.png" },
  { nome: "NOSSABET", dominio: "nossa.bet.br", icone: null },
  { nome: "NOVIBET", dominio: "novibet.bet.br", icone: "/casas/novibet.png" },
  { nome: "OBABET", dominio: "obabet.bet.br", icone: "/casas/obabet.png" },
  { nome: "OLEYBET", dominio: "oleybet.bet.br", icone: "/casas/oleybet.png" },
  { nome: "ONABET", dominio: "ona.bet.br", icone: "/casas/ona.png" },
  { nome: "P9", dominio: "p9.bet.br", icone: "/casas/p9.png" },
  { nome: "PAGOL", dominio: "pagol.bet.br", icone: "/casas/pagol.png" },
  { nome: "PAPIGAMES", dominio: "papigames.bet.br", icone: null },
  { nome: "PIN", dominio: "pin.bet.br", icone: "/casas/pin.png" },
  { nome: "PINNACLE", dominio: "pinnacle.bet.br", icone: "/casas/pinnacle.png" },
  { nome: "PITACO", dominio: "pitaco.bet.br", icone: "/casas/pitaco.png" },
  { nome: "PIXBET", dominio: "pix.bet.br", icone: "/casas/pix.png" },
  { nome: "PLAY", dominio: "play.bet.br", icone: "/casas/play.png" },
  { nome: "PLAYUZU", dominio: "playuzu.bet.br", icone: "/casas/playuzu.png" },
  { nome: "PQ777", dominio: "pq777.bet.br", icone: null },
  { nome: "QGBET", dominio: "qg.bet.br", icone: "/casas/qg.png" },
  { nome: "R7", dominio: "r7.bet.br", icone: "/casas/r7.png" },
  { nome: "RdP", dominio: "rdp.bet.br", icone: "/casas/rdp.png" },
  { nome: "REALS", dominio: "reals.bet.br", icone: "/casas/reals.png" },
  { nome: "RECEBA", dominio: "receba.bet.br", icone: "/casas/receba.png" },
  { nome: "REI DO PITACO", dominio: "reidopitaco.bet.br", icone: "/casas/reidopitaco.png" },
  { nome: "RICOBET", dominio: "rico.bet.br", icone: "/casas/rico.png" },
  { nome: "RIVALO", dominio: "rivalo.bet.br", icone: "/casas/rivalo.png" },
  { nome: "SEGURO BET", dominio: "seguro.bet.br", icone: "/casas/seguro.png" },
  { nome: "SEUBET", dominio: "seu.bet.br", icone: "/casas/seu.png" },
  { nome: "SORTENABET", dominio: "sortenabet.bet.br", icone: "/casas/sortenabet.png" },
  { nome: "SORTE ONLINE", dominio: "sorteonline.bet.br", icone: "/casas/sorteonline.png" },
  { nome: "SPORTINGBET", dominio: "sportingbet.bet.br", icone: "/casas/sportingbet.png" },
  { nome: "SPORTYBET", dominio: "sporty.bet.br", icone: "/casas/sporty.png" },
  { nome: "STAKE", dominio: "stake.bet.br", icone: "/casas/stake.png" },
  { nome: "STARTBET", dominio: "start.bet.br", icone: "/casas/start.png" },
  { nome: "SUPER", dominio: "super.bet.br", icone: null },
  { nome: "SUPERBET", dominio: "superbet.bet.br", icone: "/casas/superbet.png" },
  { nome: "SUPREMABET", dominio: "suprema.bet.br", icone: "/casas/suprema.png" },
  { nome: "TIGER.BET", dominio: "tiger.bet.br", icone: null },
  { nome: "TIVOBET", dominio: "tivo.bet.br", icone: "/casas/tivo.png" },
  { nome: "TRADICIONAL", dominio: "tradicional.bet.br", icone: "/casas/tradicional.png" },
  { nome: "TROPINO", dominio: "tropino.bet.br", icone: null },
  { nome: "ULTRABET", dominio: "ultra.bet.br", icone: "/casas/ultra.png" },
  { nome: "UPBETBR", dominio: "up.bet.br", icone: "/casas/up.png" },
  { nome: "VAIDEBET", dominio: "vaidebet.bet.br", icone: "/casas/vaidebet.png" },
  { nome: "VBET", dominio: "vbet.bet.br", icone: "/casas/vbet.png" },
  { nome: "VERA", dominio: "vera.bet.br", icone: "/casas/vera.png" },
  { nome: "VERSUSBET", dominio: "versus.bet.br", icone: "/casas/versus.png" },
  { nome: "VERT", dominio: "vert.bet.br", icone: null },
  { nome: "VIVARO", dominio: "vivaro.bet.br", icone: null },
  { nome: "VIVASORTE", dominio: "vivasorte.bet.br", icone: "/casas/vivasorte.png" },
  { nome: "VS - VERSUS", dominio: "versus.bet.br", icone: "/casas/versus.png" },
  { nome: "VUPI", dominio: "vupi.bet.br", icone: "/casas/vupi.png" },
  { nome: "WJCASINO", dominio: "wjcasino.bet.br", icone: "/casas/wjcasino.png" },
  { nome: "XBET CAIXA", dominio: "xbetcaixa.bet.br", icone: null },
  { nome: "XX", dominio: "xx.bet.br", icone: "/casas/xx.png" },
];

/** Sem acento, sem espaço e sem pontuação: "Bet 365" e "BET365" batem. */
export function normalizarCasa(texto: string) {
  return texto
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}
